<?php

namespace BackBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMulti($find)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.titre LIKE :find')->orWhere('m.text LIKE :find')->orWhere('m.lastModification LIKE :find')
            ->setParameter(':find',"%$find%");
        return $q->getQuery()->getResult();
    }

    public function findByName($find)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.titre LIKE :find')
            ->setParameter(':find',"%$find%");
        return $q->getQuery()->getResult();
    }

}
