<?php

namespace BackBundle\Repository;

/**
 * ArticlesCommentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesCommentairesRepository extends \Doctrine\ORM\EntityRepository
{
}
