<?php

namespace BackBundle\Repository;

/**
 * EventParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventParticipantsRepository extends \Doctrine\ORM\EntityRepository
{
}
