<?php

namespace BackBundle\Repository;

/**
 * EvennementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvennementRepository extends \Doctrine\ORM\EntityRepository
{



    public function findbyName($name){
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.titre LIKE :nom')
            ->setParameter('nom','%'.$name.'%')
            ->getQuery();
        return $qb;
    }

}

